### ISSUE TITLE
Search method for a range.

### ISSUE THREAD

**Issue by Ayush-Asutkar** [shandysulen/B-Plus-Tree#1]
Instead of searching linearly, we can use binary search. 
Find the key which is just lower than the lowerBound variable, and find the key which is just greater than the upperBound variable. And then iterate in this range linearly.

https://github.com/shandysulen/B-Plus-Tree/blob/40d3944257d466f1c7c0c8fcf5a8b7b5de41bc04/bplustree.java#L665

**Comment by shandysulen** [comment]
Hey Ayush, appreciate the issue! However, I'm not currently working on this repo, so the best path forward might be to fork this repo to implement your binary search idea.
